module.exports.errorCode = {
    applicationError: 500,
    dbError: 10005,
    invalidRequest: 10006,
    phoneExists:10007,
    emailExists:10008,
    invalidUserType: 10009,
    noUser:10010,
    invalidUserId:10011,
    discountExists:10012,
    noDiscount:10013,
    invalidDiscountId:10014,
    invalidCouponId:10015,
    noCoupon:10016,
    couponExists:10017,
    packageExists:10018,
    noPackageExists:10019,
    noPackageItemExists:10020,
    invalidPackage:10021,
    invalidCoupon : 10022,
    inactiveCoupon : 10023,
    expiredCoupon : 10024,
    noTeensPrice : 10025,
    outletDateExists : 10026,
    closeThirdShift : 10027,
    outletNotOpen : 10028,
    noAccessForUser : 10029,
    outletActive : 10030,
  };
  
  module.exports.errorMessage = {
    applicationError: "An Application Error Has Occured",
    dbError: "Database function error",
    invalidRequest: "Invalid Request",
    phoneExists:"Phone number already exists",
    emailExists:"Email Already Exists",
    invalidUserType: "Users not found for the specified user type",
    noUser:"User Does not exist",
    invalidUserId:"Invalid User Id",
    discountExists:"This Discount already exists",
    noDiscount:"Discount Does not exist",
    invalidDiscountId:"Invalid discount Id",
    invalidCouponId:"Invalid Coupon Id",
    noCoupon:'Coupon Does not exist',
    couponExists:"This Coupon already exists",
    packageExists:"This Package already exists",
    noPackageExists:"Package Does not exist",
    noPackageItemExists:"Item Does not exist",
    invalidPackage:"Invalid Package Id",
    invalidCoupon : "This Coupon does not exists",
    inactiveCoupon : "Coupon is Inactive",
    expiredCoupon : "Coupon has expired",
    noTeensPrice : "There is no Teens Price for this package",
    outletDateExists:"This date already exists",
    closeThirdShift:"Please Close the Third Shift",
    outletNotOpen:"This Outlet is not open",
    noAccessForUser:"This User Cannot access shift operations",
    outletActive : "This Outlet is Active"
  };